# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0add2772c27334365f4b16e6534e199b826620d633f09a2d1671525dc8897ab56e569b4ed9c95aa844fed063eb60840c4f9cf1b359339229157cd3a02bb876c8

test:
  secret_key_base: d9d1034fbe1501d8edc9612184690c8c3e17a0c4ef8500a6baa2d752852e5ca9c0b1ab0023da0fdbe1d55e6e08e73976b778adbeb26999e4602ce9af9800fe5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
